### ISSUE TITLE
Add support for Zed editor

### ISSUE THREAD

**Issue by agnelnieves** [wesbos/cobalt2-vscode#241]
https://zed.dev/

**Comment by wesbos** [comment]
Last time I checked they dont support external or user themes?

**Comment by wesbos** [comment]
Yeah - looks like no way to make a theme yet https://zed.dev/docs/themes

**Comment by palashmon** [comment]
Also, other popular vscode themes have started importing to Zed like **Dracula** theme:
- https://github.com/dracula/zed

Hopefully, _user themes_ will soon be included in the regular Zed build.

**Comment by AielloChan** [comment]
The support extensions now, Cobalt2 theme will be the best!

**Comment by AielloChan** [comment]
> Zed now support extensions, Cobalt2 theme will be the best!

https://github.com/zed-industries/extensions/issues/238

**Comment by nazarhussain** [comment]
Started working on it https://github.com/nazarhussain/cobalt2-zed, not fully matured but seems to match really nice.

**Comment by AielloChan** [comment]
> Started working on it https://github.com/nazarhussain/cobalt2-zed, not fully matured but seems to match really nice.
> 
> @wesbos If you want to take it forward I can transfer the repo to you.

looks nice bro. we should publish it!

**Comment by ickynavigator** [comment]
@wesbos looks like zed now has a theme importer - https://zed.dev/blog/user-themes-now-in-preview

**Comment by mrpmohiburrahman** [comment]
Hi, @wesbos ,

I’ve added support for the Cobalt2 theme in Zed. You can check it out in this [pull request](https://github.com/zed-industries/extensions/pull/1275) or this [repo](https://github.com/mrpmohiburrahman/cobalt2-zed) 

The repo was initially transferred to me by @nazarhussain, and I’ve made some updates.
Would you prefer I transfer it to you?

Let me know how you’d like to proceed.

**Comment by wesbos** [comment]
@mrpmohiburrahman great thanks - would love to get control over it!

**Comment by mrpmohiburrahman** [comment]
> @mrpmohiburrahman great thanks - would love to get control over it!

Done, you should be getting a notification email.

**Comment by wesbos** [comment]
@mrpmohiburrahman Crap sorry I didnt accept fast enough, could you try it again?

**Comment by mrpmohiburrahman** [comment]
> @mrpmohiburrahman Crap sorry I didnt accept fast enough, could you try it again?

Done, please, check email.

**Comment by wesbos** [comment]
Also PR'd the submodule path.  https://github.com/zed-industries/extensions/pull/1301

Thanks everyone!

**Comment by ickynavigator** [comment]
@wesbos looks like you still need to sign the cla on Zed's end (incase you missed it)
